[package]
name = "scrapyard_engine"
version = "0.1.0"
authors = ["Aryeh <aryehzinn@hotmail.com>"]
edition = "2018"
build = "build.rs"

[workspace]

[dependencies]
failure = "0.1.5"
engine = {path = "src/engine"}
