[package]
name = "rendering_engine"
version = "0.1.0"
authors = ["Aryeh <aryehzinn@hotmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
serde = {version = "1.0.89", features = ["derive"]}
failure = "0.1.5"
sdl2 = {version = "0.32.2"}

